import Head from "next/head";
import { BiCalendarPlus, BiX, BiCheck } from "react-icons/bi";
import Table from "../components/table";
import Form from "../components/form";
import { useSelector, useDispatch } from "react-redux";
import { toggleChangeAction, deleteAction } from "../redux/reducer";
import { deleteUser, getUsers } from "../lib/helper";
import { useQuery, useQueryClient } from "react-query";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const queryClient = useQueryClient();

  const { isLoading, isError } = useQuery("users", getUsers);

  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  const deleteHandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryClient.prefetchQuery("users", getUsers);
      await dispatch(deleteAction(null));
    }
  };

  const cancelHandler = async () => {
    console.log("cancel");
    await dispatch(deleteAction(null));
  };

  if (isLoading) return <div>Appointments are loading...</div>;
  if (isError) return <div>Error: {error}</div>;

  return (
    <section>
      <Head>
        <title>Pet Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-5 pb-1 mx-10">
        <h1 className="text-2xl md:text-2xl text-left font-bold py-2">
          Pet Clinic
        </h1>

        <div className="container mr-auto flex justify-between py-5 border-b">
          <div className="left flex">
            <button
              className="flex justify-center bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-indigo-500"
              onClick={handler}
            >
              Add Appointment{" "}
              <span className="px-1">
                <BiCalendarPlus size={23} />
              </span>
            </button>
          </div>
        </div>
        {deleteId ? DeleteComponent({ deleteHandler, cancelHandler }) : <></>}

        {/* collapsable form */}
        {visible ? <Form></Form> : <></>}
      </main>

      {/* table */}
      <div className="overflow-x-auto">
        <Table></Table>
      </div>
    </section>
  );
}

function DeleteComponent({ deleteHandler, cancelHandler }) {
  return (
    <div className="flex items-center gap-2">
      <span>Are you sure?</span>
      <button
        onClick={deleteHandler}
        className="flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-green-500 hover:border-green-500 hover:text-gray-50"
      >
        Yes
        <span className="px-1">
          <BiCheck color="white" size={23} />
        </span>
      </button>
      <button
        onClick={cancelHandler}
        className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50"
      >
        No
        <span className="px-1">
          <BiX color="white" size={23} />
        </span>
      </button>
    </div>
  );
}
